#' The ctgGEMset class
#'
#' The main class used by the \pkg{cellTreeGenerator} package to hold single
#' cell gene expression data and generated tree results.  ctgGEMset extends the
#' basic [Biobase::ExpressionSet-class] class.
#'
#' This class is initialized from a matrix of gene expression values and
#' associated metadata.  Methods that operate on ctgGEMset objects
#' comprise the ctgGEM workflow.
#'
#'
#' @field cellTreeInfo a character vector of the name of the column of
#'     \code{phenoData()} to use for grouping data for
#'     \code{generate_tree(treeType = "cellTree")} in the
#'     \pkg{cellTreeGenerator} workflow
#' @field monocleInfo A character vector of parameters used by
#'     \code{generate_tree(treeType = "monocle")} in the
#'     \pkg{cellTreeGenerator} workflow
#' @field TSCANinfo A character vector of the row name of a single gene in
#'     \code{exprs()} to use for a single gene vs. pseudotime plot for
#'     \code{generate_tree(treeType = "TSCAN")} in the
#'     \pkg{cellTreeGenerator} workflow
#' @field sincellInfo A list containing named parameters used by
#'     \code{generate_tree(treeType = "sincell")} in the
#'     \pkg{cellTreeGenerator} workflow
#' @field treeList A list containing the simplified igraph representation of
#'     the trees generated by the \pkg{ctgGEM} workflow
#' @field originalTrees A list containing the trees generated by the
#'     \pkg{ctgGEM} workflow in their original formats for re-plotting
#' @name ctgGEMset
#' @rdname ctgGEMset
#' @aliases ctgGEMset-class
#' @exportClass ctgGEMset
#' @import Biobase
#' @examples
#' # load HSMMSingleCell package
#' library(HSMMSingleCell)
#'
#' # load the data
#' data(HSMM_expr_matrix)
#' data(HSMM_sample_sheet)
#' data(HSMM_gene_annotation)
#'
#' # convert data
#' library(Biobase)
#' pd <- AnnotatedDataFrame(data = HSMM_sample_sheet)
#' fd <- AnnotatedDataFrame(data = HSMM_gene_annotation)
#'
#' # construct a ctgGEMset
#' dataSet <- newctgGEMset(exprsData = HSMM_expr_matrix,
#'                         phenoData = pd,
#'                         featureData = fd)

setClass(
    "ctgGEMset",
    contains = "ExpressionSet",
    slots = c(
        cellTreeInfo = "character",
        monocleInfo = "list",
        TSCANinfo = "character",
        sincellInfo = "list",
        treeList = "list",
        originalTrees = "list"
    ),
    prototype = prototype(new(
        "VersionedBiobase",
        versions = c(Biobase::classVersion("ExpressionSet"),
                        ctgGEMset = "0.1.0")
    ))
)

#' Creates a new ctgGEMset object.
#'
#' @param exprsData expression data matrix for an experiment
#' @param phenoData an AnnotatedDataFrame containing attributes of individual
#'     cells
#' @param featureData an AnnotatedDataFrame containing attributes of features
#'     (e.g. genes)
#' @return a new ctgGEMset object
#' @importFrom Biobase annotatedDataFrameFrom assayDataNew
#' @export
#' @examples
#' # load HSMMSingleCell package
#' library(HSMMSingleCell)
#'
#' # load the data
#' data(HSMM_expr_matrix)
#' data(HSMM_sample_sheet)
#' data(HSMM_gene_annotation)
#'
#' # convert data
#' library(Biobase)
#' pd <- AnnotatedDataFrame(data = HSMM_sample_sheet)
#' fd <- AnnotatedDataFrame(data = HSMM_gene_annotation)
#'
#' # construct a ctgGEMset
#' dataSet <- newctgGEMset(exprsData = HSMM_expr_matrix,
#'                         phenoData = pd,
#'                         featureData = fd)
newctgGEMset <- function(exprsData, phenoData=NULL, featureData=NULL)
{
    if (!is(exprsData, "matrix")) {
        stop("Error: argument exprsData must be a matrix")
    }

    if (is.null(phenoData))
        phenoData <-
            annotatedDataFrameFrom(exprsData, byrow = FALSE)
    if (is.null(featureData))
        featureData <-
            annotatedDataFrameFrom(exprsData, byrow = TRUE)

    cs <- new(
        "ctgGEMset",
        assayData = assayDataNew("environment", exprs = exprsData),
        phenoData = phenoData,
        featureData = featureData
    )

    cs
}
